In [1]:
import pandas as pd
import numpy as np
from glob import glob
import os

import seaborn as sns
import matplotlib.pyplot as plt

from scipy import stats

In [2]:
energy_data = pd.read_csv("E:/Project/Submissions/Datasets/Energy_processed.csv")
weather_data = pd.read_csv("E:/Project/Submissions/Datasets/Weather_processed.csv")

In [3]:
energy_data.columns

Index(['Unnamed: 0', 'day', 'energy_median', 'energy_mean', 'energy_max',
       'energy_std', 'energy_sum', 'energy_min'],
      dtype='object')

In [4]:
weather_data.columns

Index(['day', 'time', 'temperatureMax', 'windBearing', 'dewPoint',
       'cloudCover', 'windSpeed', 'pressure', 'apparentTemperatureHigh',
       'visibility', 'humidity', 'apparentTemperatureLow',
       'apparentTemperatureMax', 'uvIndex', 'time.1', 'temperatureLow',
       'temperatureMin', 'temperatureHigh', 'apparentTemperatureMin',
       'moonPhase', 'clear-day', 'cloudy', 'fog', 'partly-cloudy-day',
       'partly-cloudy-night', 'wind', 'rain', 'snow'],
      dtype='object')

In [5]:
energy_data.head()

,Unnamed: 0,day,energy_median,energy_mean,energy_max,energy_std,energy_sum,energy_min
0,0,2011-11-24,0.225,0.252812,0.625,0.135267,12.135,0.092
1,1,2011-11-24,0.048,0.048000,0.049,0.000583,2.304,0.047
2,2,2011-11-24,0.125,0.174875,0.611,0.130562,8.394,0.036
3,3,2011-11-24,0.076,0.096250,0.279,0.068798,4.620,0.023
4,4,2011-11-24,0.291,0.297042,0.769,0.112216,14.258,0.127

In [6]:
weather_data.head()

,day,time,temperatureMax,windBearing,dewPoint,cloudCover,windSpeed,pressure,apparentTemperatureHigh,visibility,...,apparentTemperatureMin,moonPhase,clear-day,cloudy,fog,partly-cloudy-day,partly-cloudy-night,wind,rain,snow
0,2011-11-11,23:00:00,11.96,123,9.40,0.79,3.88,1016.08,10.87,3.30,...,6.48,0.52,False,False,True,False,False,False,True,False
1,2011-11-12,23:00:00,8.59,198,4.49,0.56,3.94,1007.71,5.62,12.09,...,0.11,0.53,False,False,False,True,False,False,True,False
2,2011-11-13,23:00:00,10.33,225,5.47,0.85,3.54,1032.76,10.33,13.39,...,5.59,0.10,False,False,False,True,False,False,True,False
3,2011-11-14,23:00:00,8.07,232,3.69,0.32,3.00,1012.12,5.33,11.89,...,0.46,0.25,False,False,False,False,False,True,True,False
4,2011-11-15,23:00:00,8.22,252,2.79,0.37,4.46,1028.17,5.02,13.16,...,-0.51,0.99,False,False,False,False,True,False,True,False

In [21]:
merged_data = pd.DataFrame.merge(energy_data, weather_data, left_on='day', right_on='day', how='inner')  # Use 'outer' if needed
#merge_dataset = pd.DataFrame.merge(daywise_data,weather_final, left_on='day', right_on='day', how='inner')
#merge_dataset

In [22]:
merged_data

,Unnamed: 0,day,energy_median,energy_mean,energy_max,energy_std,energy_sum,energy_min,time,temperatureMax,...,apparentTemperatureMin,moonPhase,clear-day,cloudy,fog,partly-cloudy-day,partly-cloudy-night,wind,rain,snow
0,0,2011-11-24,0.2250,0.252812,0.625,0.135267,12.135,0.092,23:00:00,15.57,...,9.01,0.21,False,False,False,True,False,False,True,False
1,1,2011-11-24,0.0480,0.048000,0.049,0.000583,2.304,0.047,23:00:00,15.57,...,9.01,0.21,False,False,False,True,False,False,True,False
2,2,2011-11-24,0.1250,0.174875,0.611,0.130562,8.394,0.036,23:00:00,15.57,...,9.01,0.21,False,False,False,True,False,False,True,False
3,3,2011-11-24,0.0760,0.096250,0.279,0.068798,4.620,0.023,23:00:00,15.57,...,9.01,0.21,False,False,False,True,False,False,True,False
4,4,2011-11-24,0.2910,0.297042,0.769,0.112216,14.258,0.127,23:00:00,15.57,...,9.01,0.21,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2949619,2949619,2014-02-27,0.0020,0.009729,0.038,0.012880,0.467,0.000,23:00:00,9.21,...,0.76,0.01,False,False,False,True,False,False,True,False
2949620,2949620,2014-02-27,0.0820,0.159812,1.161,0.235171,7.671,0.025,23:00:00,9.21,...,0.76,0.01,False,False,False,True,False,False,True,False
2949621,2949621,2014-02-27,0.1460,0.211208,0.877,0.228802,10.138,0.023,23:00:00,9.21,...,0.76,0.01,False,False,False,True,False,False,True,False
2949622,2949622,2014-02-27,0.0295,0.038000,0.475,0.066159,1.824,0.009,23:00:00,9.21,...,0.76,0.01,False,False,False,True,False,False,True,False
2949623,2949623,2014-02-27,0.1905,0.198104,0.768,0.104475,9.509,0.082,23:00:00,9.21,...,0.76,0.01,False,False,False,True,False,False,True,False

In [9]:
# Ensure 'day' is in datetime format
merged_data['day'] = pd.to_datetime(merged_data['day'])

# Extract year, month, and day
merged_data['year'] = merged_data['day'].dt.year
merged_data['month'] = merged_data['day'].dt.month
merged_data['date'] = merged_data['day'].dt.day

In [10]:
print(merged_data.head())
print(merged_data.columns)

   Unnamed: 0        day  energy_median  energy_mean  energy_max  energy_std  \
0           0 2011-11-24          0.225     0.252812       0.625    0.135267
1           1 2011-11-24          0.048     0.048000       0.049    0.000583
2           2 2011-11-24          0.125     0.174875       0.611    0.130562
3           3 2011-11-24          0.076     0.096250       0.279    0.068798
4           4 2011-11-24          0.291     0.297042       0.769    0.112216

   energy_sum  energy_min      time  temperatureMax  ...  cloudy    fog  \
0      12.135       0.092  23:00:00           15.57  ...   False  False
1       2.304       0.047  23:00:00           15.57  ...   False  False
2       8.394       0.036  23:00:00           15.57  ...   False  False
3       4.620       0.023  23:00:00           15.57  ...   False  False
4      14.258       0.127  23:00:00           15.57  ...   False  False

   partly-cloudy-day  partly-cloudy-night   wind  rain   snow  year  month  \
0               True                False  False  True  False  2011     11
1               True                False  False  True  False  2011     11
2               True                False  False  True  False  2011     11
3               True                False  False  True  False  2011     11
4               True                False  False  True  False  2011     11

   date
0    24
1    24
2    24
3    24
4    24

[5 rows x 38 columns]
Index(['Unnamed: 0', 'day', 'energy_median', 'energy_mean', 'energy_max',
       'energy_std', 'energy_sum', 'energy_min', 'time', 'temperatureMax',
       'windBearing', 'dewPoint', 'cloudCover', 'windSpeed', 'pressure',
       'apparentTemperatureHigh', 'visibility', 'humidity',
       'apparentTemperatureLow', 'apparentTemperatureMax', 'uvIndex', 'time.1',
       'temperatureLow', 'temperatureMin', 'temperatureHigh',
       'apparentTemperatureMin', 'moonPhase', 'clear-day', 'cloudy', 'fog',
       'partly-cloudy-day', 'partly-cloudy-night', 'wind', 'rain', 'snow',
       'year', 'month', 'date'],
      dtype='object')

In [11]:
print("Daywise Data Date Range:", energy_data['day'].min(), "to", energy_data['day'].max())
print("Weather Data Date Range:", weather_data['day'].min(), "to", weather_data['day'].max())

Daywise Data Date Range: 2011-11-24 to 2014-02-27
Weather Data Date Range: 2011-11-11 to 2014-04-10

In [12]:
# Drop the 'Unnamed: 0' column
merged_data = merged_data.drop(columns=['Unnamed: 0'])

# Verify the columns
print(merged_data.columns)

Index(['day', 'energy_median', 'energy_mean', 'energy_max', 'energy_std',
       'energy_sum', 'energy_min', 'time', 'temperatureMax', 'windBearing',
       'dewPoint', 'cloudCover', 'windSpeed', 'pressure',
       'apparentTemperatureHigh', 'visibility', 'humidity',
       'apparentTemperatureLow', 'apparentTemperatureMax', 'uvIndex', 'time.1',
       'temperatureLow', 'temperatureMin', 'temperatureHigh',
       'apparentTemperatureMin', 'moonPhase', 'clear-day', 'cloudy', 'fog',
       'partly-cloudy-day', 'partly-cloudy-night', 'wind', 'rain', 'snow',
       'year', 'month', 'date'],
      dtype='object')

In [13]:
print(merged_data.isnull().sum())  # Check NaN count for each column
print("Total missing values:", merged_data.isnull().sum().sum())  # Total NaN values in the dataset

day                        0
energy_median              0
energy_mean                0
energy_max                 0
energy_std                 0
energy_sum                 0
energy_min                 0
time                       0
temperatureMax             0
windBearing                0
dewPoint                   0
cloudCover                 0
windSpeed                  0
pressure                   0
apparentTemperatureHigh    0
visibility                 0
humidity                   0
apparentTemperatureLow     0
apparentTemperatureMax     0
uvIndex                    0
time.1                     0
temperatureLow             0
temperatureMin             0
temperatureHigh            0
apparentTemperatureMin     0
moonPhase                  0
clear-day                  0
cloudy                     0
fog                        0
partly-cloudy-day          0
partly-cloudy-night        0
wind                       0
rain                       0
snow                       0
year                       0
month                      0
date                       0
dtype: int64
Total missing values: 0

In [15]:
print(merged_data.dtypes)

day                        datetime64[ns]
energy_median                     float64
energy_mean                       float64
energy_max                        float64
energy_std                        float64
energy_sum                        float64
energy_min                        float64
time                               object
temperatureMax                    float64
windBearing                         int64
dewPoint                          float64
cloudCover                        float64
windSpeed                         float64
pressure                          float64
apparentTemperatureHigh           float64
visibility                        float64
humidity                          float64
apparentTemperatureLow            float64
apparentTemperatureMax            float64
uvIndex                           float64
time.1                             object
temperatureLow                    float64
temperatureMin                    float64
temperatureHigh                   float64
apparentTemperatureMin            float64
moonPhase                         float64
clear-day                            bool
cloudy                               bool
fog                                  bool
partly-cloudy-day                    bool
partly-cloudy-night                  bool
wind                                 bool
rain                                 bool
snow                                 bool
year                                int32
month                               int32
date                                int32
dtype: object

In [16]:
# Convert boolean categorical features (0 or 1 encoding)
bool_columns = ["clear-day", "cloudy", "fog", "partly-cloudy-day", "partly-cloudy-night", 
                "wind", "rain", "snow"]
merged_data[bool_columns] = merged_data[bool_columns].astype(int)

In [17]:
corr = merged_data.select_dtypes(include=['number']).corr()

correlation = corr['energy_sum'].sort_values(ascending=False)
print(correlation)

energy_sum                 1.000000
energy_mean                1.000000
energy_median              0.881884
energy_std                 0.803889
energy_max                 0.736506
energy_min                 0.614303
year                       0.022571
windBearing                0.007294
clear-day                  0.005202
rain                       0.003805
fog                        0.002705
cloudy                     0.002607
humidity                   0.002148
visibility                 0.001094
partly-cloudy-day          0.000881
pressure                  -0.000985
wind                      -0.001424
windSpeed                 -0.002782
temperatureMax            -0.003108
temperatureHigh           -0.003134
snow                      -0.003805
moonPhase                 -0.004417
apparentTemperatureHigh   -0.004472
apparentTemperatureMax    -0.004659
temperatureLow            -0.005229
date                      -0.005479
uvIndex                   -0.005496
cloudCover                -0.005866
dewPoint                  -0.006009
apparentTemperatureLow    -0.006586
partly-cloudy-night       -0.008026
temperatureMin            -0.009404
apparentTemperatureMin    -0.009803
month                     -0.016117
Name: energy_sum, dtype: float64

In [18]:
print(merged_data.dtypes)

day                        datetime64[ns]
energy_median                     float64
energy_mean                       float64
energy_max                        float64
energy_std                        float64
energy_sum                        float64
energy_min                        float64
time                               object
temperatureMax                    float64
windBearing                         int64
dewPoint                          float64
cloudCover                        float64
windSpeed                         float64
pressure                          float64
apparentTemperatureHigh           float64
visibility                        float64
humidity                          float64
apparentTemperatureLow            float64
apparentTemperatureMax            float64
uvIndex                           float64
time.1                             object
temperatureLow                    float64
temperatureMin                    float64
temperatureHigh                   float64
apparentTemperatureMin            float64
moonPhase                         float64
clear-day                           int32
cloudy                              int32
fog                                 int32
partly-cloudy-day                   int32
partly-cloudy-night                 int32
wind                                int32
rain                                int32
snow                                int32
year                                int32
month                               int32
date                                int32
dtype: object

In [19]:
merged_data.to_csv("E:/Project/Submissions/Datasets/Final_Data.csv", index=False)  # Saves without the index column
print(f"\nProcessed dataset saved as: Final_Data.csv")

Processed dataset saved as: Final_Data.csv

In [20]:
merged_data.shape

(2949624, 37)

In [23]:
import pandas as pd

start_date = min(pd.to_datetime(energy_data['day'].min()), pd.to_datetime(weather_data['day'].min()))
end_date = max(pd.to_datetime(energy_data['day'].max()), pd.to_datetime(weather_data['day'].max()))

total_days = (end_date - start_date).days + 1  # +1 to include both start and end dates
print(f"Expected number of rows (unique dates): {total_days}")

Expected number of rows (unique dates): 882