In [1]:
import pandas as pd
import numpy as np
from glob import glob
import os

import seaborn as sns
import matplotlib.pyplot as plt

from scipy import stats

In [2]:
# Load weather dataset
weather_df = pd.read_csv("E:/Project/weather_daily_darksky.csv")  

# Check for missing values
print(weather_df.isnull().sum())

temperatureMax                 0
temperatureMaxTime             0
windBearing                    0
icon                           0
dewPoint                       0
temperatureMinTime             0
cloudCover                     1
windSpeed                      0
pressure                       0
apparentTemperatureMinTime     0
apparentTemperatureHigh        0
precipType                     0
visibility                     0
humidity                       0
apparentTemperatureHighTime    0
apparentTemperatureLow         0
apparentTemperatureMax         0
uvIndex                        1
time                           0
sunsetTime                     0
temperatureLow                 0
temperatureMin                 0
temperatureHigh                0
sunriseTime                    0
temperatureHighTime            0
uvIndexTime                    1
summary                        0
temperatureLowTime             0
apparentTemperatureMin         0
apparentTemperatureMaxTime     0
apparentTemperatureLowTime     0
moonPhase                      0
dtype: int64

In [3]:
weather_df = pd.DataFrame({'temperatureMaxTime':pd.date_range('2011-11-11 23:00:00',periods=882)})
weather_df['day'] = pd.to_datetime(weather_df['temperatureMaxTime']).dt.date
weather_df['time'] = pd.to_datetime(weather_df['temperatureMaxTime']).dt.time
weather_df

     temperatureMaxTime         day      time
0   2011-11-11 23:00:00  2011-11-11  23:00:00
1   2011-11-12 23:00:00  2011-11-12  23:00:00
2   2011-11-13 23:00:00  2011-11-13  23:00:00
3   2011-11-14 23:00:00  2011-11-14  23:00:00
4   2011-11-15 23:00:00  2011-11-15  23:00:00
..                  ...         ...       ...
877 2014-04-06 23:00:00  2014-04-06  23:00:00
878 2014-04-07 23:00:00  2014-04-07  23:00:00
879 2014-04-08 23:00:00  2014-04-08  23:00:00
880 2014-04-09 23:00:00  2014-04-09  23:00:00
881 2014-04-10 23:00:00  2014-04-10  23:00:00

[882 rows x 3 columns]

In [4]:
weather_df_original = pd.read_csv("E:/Project/weather_daily_darksky.csv")

In [5]:
weather_prefinal = pd.concat([weather_df, weather_df_original], axis = 'columns')
weather_prefinal

,temperatureMaxTime,day,time,temperatureMax,temperatureMaxTime,windBearing,icon,dewPoint,temperatureMinTime,cloudCover,...,temperatureHigh,sunriseTime,temperatureHighTime,uvIndexTime,summary,temperatureLowTime,apparentTemperatureMin,apparentTemperatureMaxTime,apparentTemperatureLowTime,moonPhase
0,2011-11-11 23:00:00,2011-11-11,23:00:00,11.96,2011-11-11 23:00:00,123,fog,9.40,2011-11-11 07:00:00,0.79,...,10.87,2011-11-11 07:12:14,2011-11-11 19:00:00,2011-11-11 11:00:00,Foggy until afternoon.,2011-11-11 19:00:00,6.48,2011-11-11 23:00:00,2011-11-11 19:00:00,0.52
1,2011-11-12 23:00:00,2011-11-12,23:00:00,8.59,2011-12-11 14:00:00,198,partly-cloudy-day,4.49,2011-12-11 01:00:00,0.56,...,8.59,2011-12-11 07:57:02,2011-12-11 14:00:00,2011-12-11 12:00:00,Partly cloudy throughout the day.,2011-12-12 07:00:00,0.11,2011-12-11 20:00:00,2011-12-12 08:00:00,0.53
2,2011-11-13 23:00:00,2011-11-13,23:00:00,10.33,2011-12-27 02:00:00,225,partly-cloudy-day,5.47,2011-12-27 23:00:00,0.85,...,10.33,2011-12-27 08:07:06,2011-12-27 14:00:00,2011-12-27 00:00:00,Mostly cloudy throughout the day.,2011-12-27 23:00:00,5.59,2011-12-27 02:00:00,2011-12-28 00:00:00,0.10
3,2011-11-14 23:00:00,2011-11-14,23:00:00,8.07,2011-12-02 23:00:00,232,wind,3.69,2011-12-02 07:00:00,0.32,...,7.36,2011-12-02 07:46:09,2011-12-02 12:00:00,2011-12-02 10:00:00,Partly cloudy throughout the day and breezy ov...,2011-12-02 19:00:00,0.46,2011-12-02 12:00:00,2011-12-02 19:00:00,0.25
4,2011-11-15 23:00:00,2011-11-15,23:00:00,8.22,2011-12-24 23:00:00,252,partly-cloudy-night,2.79,2011-12-24 07:00:00,0.37,...,7.93,2011-12-24 08:06:15,2011-12-24 15:00:00,2011-12-24 13:00:00,Mostly cloudy throughout the day.,2011-12-24 19:00:00,-0.51,2011-12-24 23:00:00,2011-12-24 20:00:00,0.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,2014-04-06 23:00:00,2014-04-06,23:00:00,9.03,2014-01-26 16:00:00,233,partly-cloudy-day,2.39,2014-01-26 21:00:00,0.40,...,9.03,2014-01-26 07:48:49,2014-01-26 16:00:00,2014-01-26 11:00:00,Mostly cloudy until evening.,2014-01-27 05:00:00,-1.30,2014-01-26 15:00:00,2014-01-27 04:00:00,0.84
878,2014-04-07 23:00:00,2014-04-07,23:00:00,10.31,2014-02-27 14:00:00,224,partly-cloudy-day,3.08,2014-02-27 23:00:00,0.32,...,10.31,2014-02-27 06:51:45,2014-02-27 14:00:00,2014-02-27 12:00:00,Partly cloudy until evening.,2014-02-28 02:00:00,1.41,2014-02-27 14:00:00,2014-02-28 02:00:00,0.93
879,2014-04-08 23:00:00,2014-04-08,23:00:00,18.97,2014-03-09 14:00:00,172,partly-cloudy-night,4.30,2014-03-09 07:00:00,0.04,...,18.97,2014-03-09 06:29:49,2014-03-09 14:00:00,2014-03-09 12:00:00,Partly cloudy in the evening.,2014-03-10 05:00:00,7.08,2014-03-09 14:00:00,2014-03-10 06:00:00,0.28
880,2014-04-09 23:00:00,2014-04-09,23:00:00,8.83,2014-02-12 16:00:00,210,wind,1.94,2014-02-12 01:00:00,0.59,...,8.83,2014-02-12 07:21:44,2014-02-12 16:00:00,2014-02-12 10:00:00,Mostly cloudy until evening and breezy through...,2014-02-13 05:00:00,-1.20,2014-02-12 16:00:00,2014-02-13 02:00:00,0.42
881,2014-04-10 23:00:00,2014-04-10,23:00:00,9.90,2014-02-15 12:00:00,233,wind,2.95,2014-02-15 23:00:00,0.35,...,9.90,2014-02-15 07:16:06,2014-02-15 12:00:00,2014-02-15 10:00:00,Windy and mostly cloudy until afternoon.,2014-02-16 07:00:00,1.77,2014-02-15 12:00:00,2014-02-16 07:00:00,0.52

In [6]:
weather_prefinal = weather_prefinal.drop([
    'temperatureMaxTime',
    'temperatureMinTime', 'apparentTemperatureMinTime',
    'apparentTemperatureHighTime', 'sunsetTime',
    'sunriseTime', 'temperatureHighTime', 'uvIndexTime',
    'summary', 'temperatureLowTime',
    'apparentTemperatureMaxTime', 'apparentTemperatureLowTime'
], axis='columns')

In [7]:
weather_prefinal

,day,time,temperatureMax,windBearing,icon,dewPoint,cloudCover,windSpeed,pressure,apparentTemperatureHigh,...,humidity,apparentTemperatureLow,apparentTemperatureMax,uvIndex,time,temperatureLow,temperatureMin,temperatureHigh,apparentTemperatureMin,moonPhase
0,2011-11-11,23:00:00,11.96,123,fog,9.40,0.79,3.88,1016.08,10.87,...,0.95,10.87,11.96,1.0,2011-11-11 00:00:00,10.87,8.85,10.87,6.48,0.52
1,2011-11-12,23:00:00,8.59,198,partly-cloudy-day,4.49,0.56,3.94,1007.71,5.62,...,0.88,-0.64,5.72,1.0,2011-12-11 00:00:00,3.09,2.48,8.59,0.11,0.53
2,2011-11-13,23:00:00,10.33,225,partly-cloudy-day,5.47,0.85,3.54,1032.76,10.33,...,0.74,5.52,10.33,0.0,2011-12-27 00:00:00,8.03,8.03,10.33,5.59,0.10
3,2011-11-14,23:00:00,8.07,232,wind,3.69,0.32,3.00,1012.12,5.33,...,0.87,3.26,5.33,1.0,2011-12-02 00:00:00,6.33,2.56,7.36,0.46,0.25
4,2011-11-15,23:00:00,8.22,252,partly-cloudy-night,2.79,0.37,4.46,1028.17,5.02,...,0.80,4.37,5.32,1.0,2011-12-24 00:00:00,7.45,3.17,7.93,-0.51,0.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,2014-04-06,23:00:00,9.03,233,partly-cloudy-day,2.39,0.40,4.55,1002.10,5.99,...,0.79,-2.02,5.99,1.0,2014-01-26 00:00:00,2.56,3.26,9.03,-1.30,0.84
878,2014-04-07,23:00:00,10.31,224,partly-cloudy-day,3.08,0.32,4.14,1007.02,10.31,...,0.74,0.82,10.31,2.0,2014-02-27 00:00:00,3.43,3.93,10.31,1.41,0.93
879,2014-04-08,23:00:00,18.97,172,partly-cloudy-night,4.30,0.04,2.78,1022.44,18.97,...,0.58,4.12,18.97,3.0,2014-03-09 00:00:00,5.04,7.65,18.97,7.08,0.28
880,2014-04-09,23:00:00,8.83,210,wind,1.94,0.59,7.24,994.27,4.73,...,0.75,0.05,4.73,1.0,2014-02-12 00:00:00,4.14,3.03,8.83,-1.20,0.42
881,2014-04-10,23:00:00,9.90,233,wind,2.95,0.35,9.96,988.63,5.79,...,0.69,-1.03,5.79,1.0,2014-02-15 00:00:00,2.34,5.38,9.90,1.77,0.52

In [8]:
#according to weather_drop_time.info(), here Datatype of icon and precipType columns are object and string data:
#now we require to use 'hot_encoding' by get_dummies function:
icon = pd.get_dummies(weather_prefinal.icon)
icon

preciptype = pd.get_dummies(weather_prefinal.precipType)
preciptype

weather_add_icon = pd.concat([weather_prefinal, icon ], axis = 'columns')
weather_add_icon

weather_add_precip = pd.concat([weather_add_icon, preciptype  ], axis = 'columns')
weather_add_precip

weather_final = weather_add_precip.drop(['precipType', 'icon'], axis = 'columns')
weather_final

,day,time,temperatureMax,windBearing,dewPoint,cloudCover,windSpeed,pressure,apparentTemperatureHigh,visibility,...,apparentTemperatureMin,moonPhase,clear-day,cloudy,fog,partly-cloudy-day,partly-cloudy-night,wind,rain,snow
0,2011-11-11,23:00:00,11.96,123,9.40,0.79,3.88,1016.08,10.87,3.30,...,6.48,0.52,False,False,True,False,False,False,True,False
1,2011-11-12,23:00:00,8.59,198,4.49,0.56,3.94,1007.71,5.62,12.09,...,0.11,0.53,False,False,False,True,False,False,True,False
2,2011-11-13,23:00:00,10.33,225,5.47,0.85,3.54,1032.76,10.33,13.39,...,5.59,0.10,False,False,False,True,False,False,True,False
3,2011-11-14,23:00:00,8.07,232,3.69,0.32,3.00,1012.12,5.33,11.89,...,0.46,0.25,False,False,False,False,False,True,True,False
4,2011-11-15,23:00:00,8.22,252,2.79,0.37,4.46,1028.17,5.02,13.16,...,-0.51,0.99,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,2014-04-06,23:00:00,9.03,233,2.39,0.40,4.55,1002.10,5.99,11.97,...,-1.30,0.84,False,False,False,True,False,False,True,False
878,2014-04-07,23:00:00,10.31,224,3.08,0.32,4.14,1007.02,10.31,12.04,...,1.41,0.93,False,False,False,True,False,False,True,False
879,2014-04-08,23:00:00,18.97,172,4.30,0.04,2.78,1022.44,18.97,10.62,...,7.08,0.28,False,False,False,False,True,False,True,False
880,2014-04-09,23:00:00,8.83,210,1.94,0.59,7.24,994.27,4.73,11.80,...,-1.20,0.42,False,False,False,False,False,True,True,False
881,2014-04-10,23:00:00,9.90,233,2.95,0.35,9.96,988.63,5.79,12.38,...,1.77,0.52,False,False,False,False,False,True,True,False

In [9]:
print(weather_final.info())  # Check data types and missing values
print(weather_final.head())  # View first few rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   day                      882 non-null    object
 1   time                     882 non-null    object
 2   temperatureMax           882 non-null    float64
 3   windBearing              882 non-null    int64
 4   dewPoint                 882 non-null    float64
 5   cloudCover               881 non-null    float64
 6   windSpeed                882 non-null    float64
 7   pressure                 882 non-null    float64
 8   apparentTemperatureHigh  882 non-null    float64
 9   visibility               882 non-null    float64
 10  humidity                 882 non-null    float64
 11  apparentTemperatureLow   882 non-null    float64
 12  apparentTemperatureMax   882 non-null    float64
 13  uvIndex                  881 non-null    float64
 14  time                     882 non-null    object
 15  temperatureLow           882 non-null    float64
 16  temperatureMin           882 non-null    float64
 17  temperatureHigh          882 non-null    float64
 18  apparentTemperatureMin   882 non-null    float64
 19  moonPhase                882 non-null    float64
 20  clear-day                882 non-null    bool
 21  cloudy                   882 non-null    bool
 22  fog                      882 non-null    bool
 23  partly-cloudy-day        882 non-null    bool
 24  partly-cloudy-night      882 non-null    bool
 25  wind                     882 non-null    bool
 26  rain                     882 non-null    bool
 27  snow                     882 non-null    bool
dtypes: bool(8), float64(16), int64(1), object(3)
memory usage: 144.8+ KB
None
          day      time  temperatureMax  windBearing  dewPoint  cloudCover  \
0  2011-11-11  23:00:00           11.96          123      9.40        0.79
1  2011-11-12  23:00:00            8.59          198      4.49        0.56
2  2011-11-13  23:00:00           10.33          225      5.47        0.85
3  2011-11-14  23:00:00            8.07          232      3.69        0.32
4  2011-11-15  23:00:00            8.22          252      2.79        0.37

   windSpeed  pressure  apparentTemperatureHigh  visibility  ...  \
0       3.88   1016.08                    10.87        3.30  ...
1       3.94   1007.71                     5.62       12.09  ...
2       3.54   1032.76                    10.33       13.39  ...
3       3.00   1012.12                     5.33       11.89  ...
4       4.46   1028.17                     5.02       13.16  ...

   apparentTemperatureMin  moonPhase  clear-day  cloudy    fog  \
0                    6.48       0.52      False   False   True
1                    0.11       0.53      False   False  False
2                    5.59       0.10      False   False  False
3                    0.46       0.25      False   False  False
4                   -0.51       0.99      False   False  False

   partly-cloudy-day  partly-cloudy-night   wind  rain   snow
0              False                False  False  True  False
1               True                False  False  True  False
2               True                False  False  True  False
3              False                False   True  True  False
4              False                 True  False  True  False

[5 rows x 28 columns]

In [10]:
weather_final['day'] = pd.to_datetime(weather_final['day'])
weather_final

,day,time,temperatureMax,windBearing,dewPoint,cloudCover,windSpeed,pressure,apparentTemperatureHigh,visibility,...,apparentTemperatureMin,moonPhase,clear-day,cloudy,fog,partly-cloudy-day,partly-cloudy-night,wind,rain,snow
0,2011-11-11,23:00:00,11.96,123,9.40,0.79,3.88,1016.08,10.87,3.30,...,6.48,0.52,False,False,True,False,False,False,True,False
1,2011-11-12,23:00:00,8.59,198,4.49,0.56,3.94,1007.71,5.62,12.09,...,0.11,0.53,False,False,False,True,False,False,True,False
2,2011-11-13,23:00:00,10.33,225,5.47,0.85,3.54,1032.76,10.33,13.39,...,5.59,0.10,False,False,False,True,False,False,True,False
3,2011-11-14,23:00:00,8.07,232,3.69,0.32,3.00,1012.12,5.33,11.89,...,0.46,0.25,False,False,False,False,False,True,True,False
4,2011-11-15,23:00:00,8.22,252,2.79,0.37,4.46,1028.17,5.02,13.16,...,-0.51,0.99,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,2014-04-06,23:00:00,9.03,233,2.39,0.40,4.55,1002.10,5.99,11.97,...,-1.30,0.84,False,False,False,True,False,False,True,False
878,2014-04-07,23:00:00,10.31,224,3.08,0.32,4.14,1007.02,10.31,12.04,...,1.41,0.93,False,False,False,True,False,False,True,False
879,2014-04-08,23:00:00,18.97,172,4.30,0.04,2.78,1022.44,18.97,10.62,...,7.08,0.28,False,False,False,False,True,False,True,False
880,2014-04-09,23:00:00,8.83,210,1.94,0.59,7.24,994.27,4.73,11.80,...,-1.20,0.42,False,False,False,False,False,True,True,False
881,2014-04-10,23:00:00,9.90,233,2.95,0.35,9.96,988.63,5.79,12.38,...,1.77,0.52,False,False,False,False,False,True,True,False

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
numerical_cols = weather_final.select_dtypes(include=['int64', 'float64']).columns
weather_final[numerical_cols] = scaler.fit_transform(weather_final[numerical_cols])

In [11]:
print(weather_final.dtypes)

day                        datetime64[ns]
time                               object
temperatureMax                    float64
windBearing                         int64
dewPoint                          float64
cloudCover                        float64
windSpeed                         float64
pressure                          float64
apparentTemperatureHigh           float64
visibility                        float64
humidity                          float64
apparentTemperatureLow            float64
apparentTemperatureMax            float64
uvIndex                           float64
time                               object
temperatureLow                    float64
temperatureMin                    float64
temperatureHigh                   float64
apparentTemperatureMin            float64
moonPhase                         float64
clear-day                            bool
cloudy                               bool
fog                                  bool
partly-cloudy-day                    bool
partly-cloudy-night                  bool
wind                                 bool
rain                                 bool
snow                                 bool
dtype: object

print(weather_final.dtypes)

# Feature Selection

plt.figure(figsize=(12,8))
sns.heatmap(weather_final.corr(), annot=True, cmap='coolwarm')
plt.show()

In [12]:
# Check for missing values
print(weather_final.isnull().sum())

day                        0
time                       0
temperatureMax             0
windBearing                0
dewPoint                   0
cloudCover                 1
windSpeed                  0
pressure                   0
apparentTemperatureHigh    0
visibility                 0
humidity                   0
apparentTemperatureLow     0
apparentTemperatureMax     0
uvIndex                    1
time                       0
temperatureLow             0
temperatureMin             0
temperatureHigh            0
apparentTemperatureMin     0
moonPhase                  0
clear-day                  0
cloudy                     0
fog                        0
partly-cloudy-day          0
partly-cloudy-night        0
wind                       0
rain                       0
snow                       0
dtype: int64

In [13]:
# Fill missing values with the median
#weather_final.fillna(weather_final.median(), inplace=True)
weather_final.fillna(weather_final.select_dtypes(include=['number']).median(), inplace=True)

from sklearn.preprocessing import StandardScaler
# Normalize/Scale Numeric Features
scaler = StandardScaler()
numeric_cols = weather_final.select_dtypes(include=['float64', 'int64']).columns
weather_final[numeric_cols] = scaler.fit_transform(weather_final[numeric_cols])

In [14]:
weather_final.shape

(882, 28)

In [15]:
weather_final.to_csv('E:/Project/Submissions/Datasets/Weather_Processed.csv', index=False)
print(f"\nProcessed dataset saved as: Weather_Processed.csv")

Processed dataset saved as: Weather_Processed.csv

In [16]:
weather_final

,day,time,temperatureMax,windBearing,dewPoint,cloudCover,windSpeed,pressure,apparentTemperatureHigh,visibility,...,apparentTemperatureMin,moonPhase,clear-day,cloudy,fog,partly-cloudy-day,partly-cloudy-night,wind,rain,snow
0,2011-11-11,23:00:00,11.96,123,9.40,0.79,3.88,1016.08,10.87,3.30,...,6.48,0.52,False,False,True,False,False,False,True,False
1,2011-11-12,23:00:00,8.59,198,4.49,0.56,3.94,1007.71,5.62,12.09,...,0.11,0.53,False,False,False,True,False,False,True,False
2,2011-11-13,23:00:00,10.33,225,5.47,0.85,3.54,1032.76,10.33,13.39,...,5.59,0.10,False,False,False,True,False,False,True,False
3,2011-11-14,23:00:00,8.07,232,3.69,0.32,3.00,1012.12,5.33,11.89,...,0.46,0.25,False,False,False,False,False,True,True,False
4,2011-11-15,23:00:00,8.22,252,2.79,0.37,4.46,1028.17,5.02,13.16,...,-0.51,0.99,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,2014-04-06,23:00:00,9.03,233,2.39,0.40,4.55,1002.10,5.99,11.97,...,-1.30,0.84,False,False,False,True,False,False,True,False
878,2014-04-07,23:00:00,10.31,224,3.08,0.32,4.14,1007.02,10.31,12.04,...,1.41,0.93,False,False,False,True,False,False,True,False
879,2014-04-08,23:00:00,18.97,172,4.30,0.04,2.78,1022.44,18.97,10.62,...,7.08,0.28,False,False,False,False,True,False,True,False
880,2014-04-09,23:00:00,8.83,210,1.94,0.59,7.24,994.27,4.73,11.80,...,-1.20,0.42,False,False,False,False,False,True,True,False
881,2014-04-10,23:00:00,9.90,233,2.95,0.35,9.96,988.63,5.79,12.38,...,1.77,0.52,False,False,False,False,False,True,True,False